In [9]:
# 1*12 arrary
import numpy as np
array_test= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array_test)
print(array_test.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [16]:
# re-shape
import numpy as np
array_test= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_new=array_test.reshape(6,2)
print(array_new)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [24]:
#flatten
import numpy as np
array_test= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_test)
array_new=array_test.flatten()
print(array_new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
#transpose
import numpy as np
array_test= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_test)
array_new=array_test.transpose()
print(array_new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [32]:
#string replace
import numpy as np
text="how is class going for you"
result=np.char.replace(text,'for you','out for you with zemen')
print(result)

how is class going out for you with zemen


In [1]:
#Create a one-dimensional NumPy array containing at least ten elements
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
#Create a 2D NumPy array with a minimum of 3 rows and 4 columns
import numpy as np
arr_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
arr_3d=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
#Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval
print(arr_2d[0,1])
print(arr_3d[0,1,1])
print(arr_3d[0,:,:])
print(arr_3d[0,:,1])

2
5
[[1 2 3]
 [4 5 6]]
[2 5]


In [29]:
#Access and print various elements from 1D, 2D, and 3D arrays using positive indexing
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[4])
print(arr_2d[0,1])
print(arr_3d[0,1,1])
print(arr_3d[0,:,:])
print(arr_3d[0,:,1])

5
2
5
[[1 2 3]
 [4 5 6]]
[2 5]


In [35]:
#Perform and print some basic arithmetic operations (like addition or subtraction) using elements accessed from 1D, 2D, and 3D arrays

print(arr[4]+arr[5])
print(arr_2d[0,:]+arr_2d[1,:])
print(arr_3d)
print(arr_3d[0,1,:]+arr_3d[1,1,:])

11
[ 6  8 10 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[14 16 18]


In [36]:
# Access and print elements using negative indices in all three arrays
print(arr[-2]+arr[-3])
print(arr_2d[0,-1]+arr_2d[1,-2])
print(arr_3d)
print(arr_3d[0,1,-2]+arr_3d[1,1,-3])

17
11
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
15


     A   B   C   D
10   0   1   2   3
20   4   5   6   7
30   8   9  10  11
40  12  13  14  15


B  C  D
10  1  2  3
20  5  6  7

    A  B  C
w  10  1  5
x  20  2  6
y  30  3  7
z  40  4  8


B  C
x  2  6
y  3  7